// import './globals.css';
import { Inter } from "next/font/google";
import AuthContextProvider from "../contexts/authContext";
import { ColorModeScript, ChakraProvider } from "@chakra-ui/react";
import { Providers } from "./providers";
import theme from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeScript initialColorMode={theme.config?.initialColorMode} />
        <ChakraProvider theme={theme}>
          <Providers>
            <AuthContextProvider>
              {children}
            </AuthContextProvider>
          </Providers>
        </ChakraProvider>
      </body>
    </html>
  );
}
